In [0]:
from pyspark.sql.functions import lit
from pyspark.sql import SparkSession

In [0]:
spark = SparkSession.builder.master('local') \
                     .appName('Practice Spark') \
                     .getOrCreate()

In [0]:
df = spark.read.options(header=True, inferSchema=True) \
               .csv('/FileStore/tables/employees-1.csv') 
               
df.printSchema()

root
 |-- First Name: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- Start Date: date (nullable = true)
 |-- Last Login Time: string (nullable = true)
 |-- Salary: integer (nullable = true)
 |-- Bonus %: double (nullable = true)
 |-- Senior Management: boolean (nullable = true)
 |-- Team: string (nullable = true)

In [0]:
# Select only Gender column
df.select(df.Gender).show()

# Create new column with constant value
df.withColumn('Country', lit('USA')).show()

# Rename column
df.withColumnRenamed('Gender', 'SEX').show()

# Drop column
df.drop('Country').show()

#Change data type
df.withColumn('salary', col('salary').cast("string")).printSchema()

+------+
|Gender|
+------+
|  Male|
|  Male|
|Female|
|  Male|
|  Male|
|  Male|
|Female|
|Female|
|Female|
|Female|
|Female|
|Female|
|  Male|
|  Male|
|Female|
|Female|
|  Male|
|  Male|
|Female|
|Female|
+------+
only showing top 20 rows

+----------+------+----------+---------------+------+-------+-----------------+--------------------+-------+
|First Name|Gender|Start Date|Last Login Time|Salary|Bonus %|Senior Management|                Team|Country|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+-------+
|   Douglas|  Male|1993-08-06|       12:42 PM| 97308|  6.945|             true|           Marketing|    USA|
|    Thomas|  Male|1996-03-31|        6:53 AM| 61933|   4.17|             true|                null|    USA|
|     Maria|Female|1993-04-23|       11:17 AM|130590| 11.858|            false|             Finance|    USA|
|     Jerry|  Male|2005-03-04|        1:00 PM|138705|   9.34|             true|             Finance|    USA|
|     Larry|  Male|1998-01-24|        4:47 PM|101004|  1.389|             true|     Client Services|    USA|
|    Dennis|  Male|1987-04-18|        1:35 AM|115163| 10.125|            false|               Legal|    USA|
|      Ruby|Female|1987-08-17|        4:20 PM| 65476| 10.012|             true|             Product|    USA|
|      null|Female|2015-07-20|       10:43 AM| 45906| 11.598|             null|             Finance|    USA|
|    Angela|Female|2005-11-22|        6:29 AM| 95570| 18.523|             true|         Engineering|    USA|
|   Frances|Female|2002-08-08|        6:51 AM|139852|  7.524|             true|Business Development|    USA|
|    Louise|Female|1980-08-12|        9:01 AM| 63241| 15.132|             true|                null|    USA|
|     Julie|Female|1997-10-26|        3:19 PM|102508| 12.637|             true|               Legal|    USA|
|   Brandon|  Male|1980-12-01|        1:08 AM|112807| 17.492|             true|     Human Resources|    USA|
|      Gary|  Male|2008-01-27|       11:40 PM|109831|  5.831|            false|               Sales|    USA|
|  Kimberly|Female|1999-01-14|        7:13 AM| 41426| 14.543|             true|             Finance|    USA|
|   Lillian|Female|2016-06-05|        6:09 AM| 59414|  1.256|            false|             Product|    USA|
|    Jeremy|  Male|2010-09-21|        5:56 AM| 90370|  7.369|            false|     Human Resources|    USA|
|     Shawn|  Male|1986-12-07|        7:45 PM|111737|  6.414|            false|             Product|    USA|
|     Diana|Female|1981-10-23|       10:27 AM|132940| 19.082|            false|     Client Services|    USA|
|     Donna|Female|2010-07-22|        3:48 AM| 81014|  1.894|            false|             Product|    USA|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+-------+
only showing top 20 rows

+----------+------+----------+---------------+------+-------+-----------------+--------------------+
|First Name|   SEX|Start Date|Last Login Time|Salary|Bonus %|Senior Management|                Team|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+
|   Douglas|  Male|1993-08-06|       12:42 PM| 97308|  6.945|             true|           Marketing|
|    Thomas|  Male|1996-03-31|        6:53 AM| 61933|   4.17|             true|                null|
|     Maria|Female|1993-04-23|       11:17 AM|130590| 11.858|            false|             Finance|
|     Jerry|  Male|2005-03-04|        1:00 PM|138705|   9.34|             true|             Finance|
|     Larry|  Male|1998-01-24|        4:47 PM|101004|  1.389|             true|     Client Services|
|    Dennis|  Male|1987-04-18|        1:35 AM|115163| 10.125|            false|               Legal|
|      Ruby|Female|1987-08-17|        4:20 PM| 65476| 10.012|             true|             Product|
|      null|Female|2015-07-20|       10:43 AM| 45906| 11.598|             null|             Finance|
|    Angela|Female|2005-11-22|        6:29 AM| 95570| 18.523|             true|         Engineering|
|   Frances|Female|2002-08-08|        6:51 AM|139852|  7.524|             true|Business Development|
|    Louise|Female|1980-08-12|        9:01 AM| 63241| 15.132|             true|                null|
|     Julie|Female|1997-10-26|        3:19 PM|102508| 12.637|             true|               Legal|
|   Brandon|  Male|1980-12-01|        1:08 AM|112807| 17.492|             true|     Human Resources|
|      Gary|  Male|2008-01-27|       11:40 PM|109831|  5.831|            false|               Sales|
|  Kimberly|Female|1999-01-14|        7:13 AM| 41426| 14.543|             true|             Finance|
|   Lillian|Female|2016-06-05|        6:09 AM| 59414|  1.256|            false|             Product|
|    Jeremy|  Male|2010-09-21|        5:56 AM| 90370|  7.369|            false|     Human Resources|
|     Shawn|  Male|1986-12-07|        7:45 PM|111737|  6.414|            false|             Product|
|     Diana|Female|1981-10-23|       10:27 AM|132940| 19.082|            false|     Client Services|
|     Donna|Female|2010-07-22|        3:48 AM| 81014|  1.894|            false|             Product|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+
only showing top 20 rows

+----------+------+----------+---------------+------+-------+-----------------+--------------------+
|First Name|Gender|Start Date|Last Login Time|Salary|Bonus %|Senior Management|                Team|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+
|   Douglas|  Male|1993-08-06|       12:42 PM| 97308|  6.945|             true|           Marketing|
|    Thomas|  Male|1996-03-31|        6:53 AM| 61933|   4.17|             true|                null|
|     Maria|Female|1993-04-23|       11:17 AM|130590| 11.858|            false|             Finance|
|     Jerry|  Male|2005-03-04|        1:00 PM|138705|   9.34|             true|             Finance|
|     Larry|  Male|1998-01-24|        4:47 PM|101004|  1.389|             true|     Client Services|
|    Dennis|  Male|1987-04-18|        1:35 AM|115163| 10.125|            false|               Legal|
|      Ruby|Female|1987-08-17|        4:20 PM| 65476| 10.012|             true|             Product|
|      null|Female|2015-07-20|       10:43 AM| 45906| 11.598|             null|             Finance|
|    Angela|Female|2005-11-22|        6:29 AM| 95570| 18.523|             true|         Engineering|
|   Frances|Female|2002-08-08|        6:51 AM|139852|  7.524|             true|Business Development|
|    Louise|Female|1980-08-12|        9:01 AM| 63241| 15.132|             true|                null|
|     Julie|Female|1997-10-26|        3:19 PM|102508| 12.637|             true|               Legal|
|   Brandon|  Male|1980-12-01|        1:08 AM|112807| 17.492|             true|     Human Resources|
|      Gary|  Male|2008-01-27|       11:40 PM|109831|  5.831|            false|               Sales|
|  Kimberly|Female|1999-01-14|        7:13 AM| 41426| 14.543|             true|             Finance|
|   Lillian|Female|2016-06-05|        6:09 AM| 59414|  1.256|            false|             Product|
|    Jeremy|  Male|2010-09-21|        5:56 AM| 90370|  7.369|            false|     Human Resources|
|     Shawn|  Male|1986-12-07|        7:45 PM|111737|  6.414|            false|             Product|
|     Diana|Female|1981-10-23|       10:27 AM|132940| 19.082|            false|     Client Services|
|     Donna|Female|2010-07-22|        3:48 AM| 81014|  1.894|            false|             Product|
+----------+------+----------+---------------+------+-------+-----------------+--------------------+
only showing top 20 rows

root
 |-- First Name: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- Start Date: date (nullable = true)
 |-- Last Login Time: string (nullable = true)
 |-- salary: string (nullable = true)
 |-- Bonus %: double (nullable = true)
 |-- Senior Management: boolean (nullable = true)
 |-- Team: string (nullable = true)

In [0]:
sparkContext = spark.sparkContext
rdd =sparkContext.parallelize([1,2,3,4], 2)
print(rdd.collect())
print(rdd.getNumPartitions())
print(rdd.glom.collect())

[1, 2, 3, 4]
2

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-104374530385596> in <cell line: 5>()
      3 print(rdd.collect())
      4 print(rdd.getNumPartitions())
----> 5 print(rdd.glom.collect())

AttributeError: 'function' object has no attribute 'collect'